version: "1.0"
services:
  frontend:
    image: paperless:nginx
    build:
      dockerfile: ui/Dockerfile
    ports:
      - "8080:80"
  backend:
    image: paperless:openjdk
    build:
      dockerfile: Dockerfile
    ports:
      - "8088:8088"               #vll noch auf 8081:8081 ändern? -> siehe Architecture
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: swen3-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin  # Change to a secure username
      MINIO_ROOT_PASSWORD: minioadmin  # Change to a secure password
    command: server /data
    ports:
      - "9000:9000" # MinIO API
      - "9090:9090" # MinIO Console
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: user  # Change to a secure username
      RABBITMQ_DEFAULT_PASS: password  # Change to a secure password
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # RabbitMQ management

volumes:
  postgres_data:
  minio_data: