version: "1.0"
services:
  frontend:
    image: paperless:nginx
    build:
      dockerfile: ui/Dockerfile
    ports:
      - "8080:80"
  backend:
    image: paperless:openjdk
    build:
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: swen3-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
